server:
  port: 8761

spring:
  cloud:
    config:
      enabled: false

#hostname: localhost

eureka:
  instance:
    hostname: "${HOSTNAME:localhost}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false

